export const CONSTANTES = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_ID: "GET_ID",
  SEARCH_NAME: "SEARCH_NAME",
  FILTER_BY_CATEGORYS: "FILTER_BY_CATEGORYS",
  ORDER_PRICE: "ORDER_PRICE",
  RECETA_CREADA: "PRODUCT_CREADA",
  RECETA_NO_CREADA: "PRODUCT_NO_CREADA",
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_ONE_PRODUCT: "DELETE_ONE_PRODUCT",
  CLEAR_CART: "CLEAR_CART",
  DELETE_ALL_PRODUCT: "DELETE_ALL_PRODUCT",
  DESMONTAR_DETALLE: "DESMONTAR_DETALLE",

  GET_ALL_REVIEW: "GET_ALL_REVIEW",
  POST_PRODUCT: "POST_PRODUCT",
  POST_IMAGES: "POST_IMAGES",
  PUT_USER: "PUT:USER",
  GET_USER: "GET_USER",
  GET_USER_ID: "GET_USER_ID",

  REQUEST_CHANGE_STATUS: "REQUEST_CHANGE_STATUS",
  RECEIVE_CHANGE_STATUS: "RECEIVE_CHANGE_STATUS",
  CHANGE_STATUS: "CHANGE_STATUS",

  GET_ODERS: "GET_ODERS"
};
